name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
        dependencies:
          - "lowest"
          - "highest"
    name: Tests with PHP ${{ matrix.php-version }} and ${{ matrix.dependencies }} dependencies

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
      env:
        COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate composer
      run: composer validate

    - name: Composer install
      uses: "ramsey/composer-install@v1"
      with:
        dependency-versions: "${{ matrix.dependencies }}"
        composer-options: "${{ matrix.composer-options }}"

    - name: Run unit tests suite
      run: vendor/bin/phpunit --configuration tests/Unit/phpunit.xml.dist

    - name: Run code style suite
      run: vendor/bin/phpcs --standard=psr12 src/ --ignore=*.min.css

    - name: Run tests code style
      run: vendor/bin/phpcs --standard=psr12 tests/ --ignore=/_files/ -n
