name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-source --no-interaction --dev

    - name: Run unit tests suite
      run: php vendor/bin/phpunit --configuration tests/Unit/phpunit.xml.dist

    - name: Run code style suite
      run: php vendor/bin/phpcs --standard=psr12 src/ --ignore=*.min.css

    - name: Run tests code style
      run: php vendor/bin/phpcs --standard=psr12 tests/ --ignore=/_files/ -n
